#! /bin/sh

### BEGIN INIT INFO
# Provides:          homecon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: HomeCon initscript
### END INIT INFO

# Author: Brecht Baeten

DESC="HomeCon server"
NAME=homecon
DAEMON={env}/bin/python
DAEMON_ARGS="-m homecon --loglevel=DEBUG"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME


[ -x "$DAEMON" ] || exit 0
#[ -r /etc/default/$NAME ] && . /etc/default/$NAME
. /lib/init/vars.sh
#. /lib/lsb/init-functions

do_start()
{{
  echo "Starting HomeCon"
  start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
  case $? in
    0)
      echo "HomeCon started as daemon"
      ;;
  esac
  return $?
}}

do_stop() {{
  echo "Stopping HomeCon"
  start-stop-daemon --stop --signal 2 --quiet --remove-pidfile --pidfile $PIDFILE --exec $DAEMON
  case $? in
    0)
      echo "HomeCon stopped"
      ;;
    *)
      echo "HomeCon was not running"
      ;;
  esac
  return $?
}}

case "$1" in
  start)
    do_start
    ;;

  stop)
    do_stop
    ;;

  status)
    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
    ;;

  restart)
    do_stop
    sleep 1
    do_start
    ;;

  *)
    echo "Usage: $SCRIPTNAME {{start|stop|status|restart}}" >&2
    exit 3
    ;;
esac
